from pathlib import Path
R=Path(__file__).resolve().parents[1]
p=R/'engine.js';s=p.read_text(encoding='utf-8-sig')
s=s.replace("sentience-gameplay-v3-story-save-20260926","sentience-gameplay-v4-save-20260926").replace('version:3','version:4').replace('s?.version!==3','s?.version!==4').replace('hp:120','hp:1000')
s=s.replace('const p=library.patterns.find','const p=(level.authoredPatterns||library.patterns).find')
s=s.replace('i*160,g-h,160','i*(p.spacing||160),g-h,p.blockWidth||160').replace('90+i*160','90+i*(p.spacing||160)')
s=s.replace('baseY:y,...extra','baseY:y,region:p.region,crumble:p.region===\'roofs\'&&kind===\'floating\',...extra')
s=s.replace('hp:64,damage:8','hp:165,damage:155').replace('hp:140,damage:12','hp:420,damage:220').replace('hp:110,damage:11','hp:290,damage:175').replace('hp:650,damage:18','hp:1650,damage:280').replace('hp:820,damage:16','hp:2600,damage:310')
p.write_text(s,encoding='utf-8')
p=R/'gameplay-v2.js';s=p.read_text(encoding='utf-8-sig')
s="import {ensureGear,stats,grantGear,addXP} from './gear-system.js';\nimport {renderLoadout} from './loadout.js';\nimport {sanitizeSave} from './save-validation.js';\n"+s
s=s.replace('save=readSave(localStorage)','save=ensureGear(readSave(localStorage))')
s=s.replace("localStorage.setItem(SAVE_KEY,JSON.stringify(save));", "if(g?.mode==='endless'&&g.phase!=='finished')return;const old=localStorage.getItem(SAVE_KEY);if(old)localStorage.setItem(SAVE_KEY+'-backup',old);localStorage.setItem(SAVE_KEY,JSON.stringify(save));")
s=s.replace("function maxHP(){return 120+(save.level-1)*15+(save.stigmaEquipped?15+save.stigmaLevel*5:0)}","function maxHP(){return stats(save).hp}")
s=s.replace("$('#endless').disabled=!save.endlessUnlocked;$('#endless').textContent=save.endlessUnlocked?'ENDLESS · BẮT ĐẦU →':'ENDLESS · Chưa mở — hoàn thành Chương 7';", "$('#endless').disabled=!atlas;$('#endless').textContent='ENDLESS · THỬ THÁCH ĐỘC LẬP →';$('#endless-record').textContent=`KỶ LỤC ${save.endlessBest||0} ĐIỂM · TRANG BỊ STORY ĐƯỢC GIỮ RIÊNG`;")
a=s.index('function renderGear(){');b=s.index('function createPlayer',a)
s=s[:a]+'''function renderGear(){renderLoadout({save,changed(value){if(value){const clean=sanitizeSave(value);if(!clean)return false;try{localStorage.setItem(SAVE_KEY+'-archive-'+Date.now(),JSON.stringify(committed));save=clean;persist();renderGear();return true}catch{return false}}persist();},resume:()=>start('story'),draw(c,companion){const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);drawSprite('idle.5',companion?145:185,270,1.8,1,1,x);if(companion)drawSprite('hua.0',270,265,1.35,-1,1,x)}})}
''' + s[b:]
s=s.replace("if(mode==='endless'&&!save.endlessUnlocked)return;enableAudio();", "enableAudio();")
s=s.replace("committed=structuredClone(save);\n const world", "committed=structuredClone(save);if(mode==='endless'){save=structuredClone(save);save.weapons=['sword','spear','chain'];save.weapon='sword';save.weaponLevels={sword:1,spear:1,chain:1};}\n const world")
s=s.replace("fieldSpawned:new Set(save.defeated||[]),defeated:new Set(save.defeated||[])","fieldSpawned:new Set(mode==='story'?save.defeated:[]),defeated:new Set(mode==='story'?save.defeated:[])")
s=s.replace('nodes:chapter.nodes.map','nodes:(mode===\'story\'?chapter.nodes:[]).map')
s=s.replace('speechTime:0,parry:0','speechTime:0,speechQueue:[],storyEvents:new Set(save.storyEvents),presentationTime:0,dialogueClock:0,projectiles:[],dash:0,dashCD:0,runBuff:1,nextUpgrade:30,upgrades:0,parry:0')
s=s.replace("g.dialogueDone=done;", "g.dialogueDone=done;g.dialogueClock=0;")
s=s.replace("function showDialogue(){const line", "function showDialogue(){g.dialogueClock=0;const line")
s=s.replace("p.comboStep=p.comboTime>0?(p.comboStep%3)+1:1", "p.comboStep=p.comboTime>0?(p.comboStep%(g.dodgeCombo>0?5:3))+1:1")
s=s.replace("`${save.weapon}_attack_${p.comboStep}`", "`${save.weapon}_attack_${Math.min(3,p.comboStep)}`")
s=s.replace("if(e.hp<=0){e.dead=.65;", "if(e.hp<=0){if(g.mode==='story')addXP(save,e.kind==='boss'?180:e.kind==='elite'?35:18);e.dead=.65;")
s=s.replace("amount=Math.round(amount*((save.deaths", "const sv=stats(save);amount=Math.round(amount*100/(100+sv.def)*(1-sv.reduction)*((save.deaths")
s=s.replace("g.hp-=amount;metrics.damageTaken", "g.hp-=amount;if(sv.sets.nagazora_survivor>=3)g.survivorBuff=6;metrics.damageTaken")
s=s.replace("p.hurtTime=.22", "p.hurtTime=sv.sets.nagazora_survivor?.176:.22")
s=s.replace("save.best=Math.max(save.best,Math.floor(g.score));save.gold+=g.runGold;persist();g.phase='finished';", "g.phase='finished';save=structuredClone(committed);save.endlessBest=Math.max(save.endlessBest||0,Math.floor(g.score));persist();")
s=s.replace("Kỷ lục và vàng đã được lưu.", "Kỷ lục Endless đã lưu. Vàng và nâng cấp trong lượt này không thay đổi Story.")
s=s.replace('g.hp+35','g.hp+maxHP()*.12')
s=s.replace('save.elapsed=g.elapsed;persist();metrics.checkpoints', "save.elapsed=g.elapsed;save.storyEvents=[...g.storyEvents];if(stats(save).sets.training_memory>=2)g.p.invuln=5;persist();metrics.checkpoints")
s=s.replace("g.hp+30", "g.hp+maxHP()*.08")
s=s.replace("if(a.m===2000&&g.mode==='story'){save.equipmentUnlocked", "if(g.mode==='story'){for(const id of chapter.gearRewards?.[a.m]||[])grantGear(save,id);save.equipmentUnlocked=true;save.crystals+=3;}\n if(a.m===2000&&g.mode==='story'){save.equipmentUnlocked")
s=s.replace("save.elapsed=g.elapsed;save.checkpoint", "save.elapsed=g.elapsed;save.storyEvents=[...g.storyEvents];save.checkpoint")
s=s.replace("g.phase='dialogue';g.p.vx=0;", "g.phase='dialogue';g.speechQueue=[];g.speechTime=0;g.p.vx=0;")
s=s.replace("dialogue(event.before||", "if(g.mode==='endless'){g.phase='arena';spawnWave();return;}\n dialogue(event.before||")
s=s.replace("g.mode==='story'?chapter.physics.speed", "g.mode==='story'?chapter.physics.speed*(1+stats(save).move+(g.survivorBuff>0?.12:0))")
s=s.replace("const p=g.p;const right", "const p=g.p;if(pressed.has('KeyL')&&g.dashCD<=0&&save.weapon){g.dash=.19;g.dashCD=Math.max(.65,1.5-(save.skills.dodge||0)*.12);p.invuln=Math.max(p.invuln,.25);g.dodgeCombo=2;metric('dodge');spark(p.x,p.y-40,'#c2c0ff',7);}\n const right")
s=s.replace("if(p.attack&&p.grounded)vx*=.38;", "if(g.dash>0)vx=p.face*760;else if(p.attack&&p.grounded)vx*=.38;")
old="const dmg=Math.round((w.damage+save.weaponLevels[a.weapon]*4+(save.level-1)*3)*(a.step===3?1.4:1)*(1-armor)*(save.stigmaEquipped?1.06+save.stigmaLevel*.02:1));"
new="const v=stats(save),dmg=Math.round(v.atk*(a.weapon==='sword'?.75:a.weapon==='spear'?1.1:.55*2)*(1+v.physical)*(1+v.total+v.normal+(g.survivorBuff>0?.1:0))*(1+(save.skills.sword||0)*.05)*(a.step>=3?1.4:1)*(1-armor)*100/120*(1+Math.min(.2,g.combo*.002))*(random()<v.crit?1.5:1)*(g.mode==='endless'?g.runBuff:1));"
assert old in s;s=s.replace(old,new)
s=s.replace("hitEnemy(e,g.empowered?dmg*2:dmg,a.weapon);g.empowered=false", "hitEnemy(e,g.empowered?Math.round(dmg*(save.equippedCore==='cloth_resolve'?2.24:2)):dmg,a.weapon);if(g.empowered&&stats(save).sets.nagazora_survivor>=2)for(const other of g.enemies)if(other.hp>0&&Math.abs(other.x-e.x)<240)hitEnemy(other,Math.round(stats(save).atk*.8),'echo');g.empowered=false")
s=s.replace("const previous=g.nodes.filter", "if(n.order===0&&g.loopCount<1)continue;const previous=g.nodes.filter")
s=s.replace("n.destroyed=true;g.shake=12", "n.destroyed=true;g.storyEvents.add('node:'+n.id);g.speechQueue=[];g.speechTime=0;if(n.order===0){g.rescueState='freed';say('Fu Hua','...Tuổi trẻ? Cậu... ở đó sao?');}g.shake=12")
s=s.replace("e.hurt>0&&!['boss','elite'].includes(e.kind)", "e.hurt>0&&!['boss','elite','mini'].includes(e.kind)")
s=s.replace("else if(Math.abs(p.x-e.x)<e.reach+18", "else if(e.move==='arrow'){g.projectiles.push({x:e.x,y:e.y-62,vx:e.face*400,life:3,damage:e.damage});}else if(Math.abs(p.x-e.x)<e.reach+18")
s=s.replace("if(distance>e.reach*.78&&e.attackTimer<=0)", "if(distance>(e.kind==='enemy'?280:e.reach*.78)&&e.attackTimer<=0)")
s=s.replace("if(distance<e.reach+12&&e.cooldown<=0", "if(distance<(e.kind==='enemy'?540:e.reach+12)&&e.cooldown<=0")
s=s.replace("e.move=e.kind==='elite'||", "e.move=e.kind==='enemy'?'arrow':e.kind==='elite'||")
s=s.replace("e.telegraph=e.kind==='boss'?", "e.telegraph=e.kind==='enemy'?.9:e.kind==='boss'?")
s=s.replace("g.loopCount++;g.wave=0;spawnWave();say('Senti','Chúng lại xuất hiện! Phải chém nút sáng trên cột đèn!');", "g.loopCount++;g.rescueState='failed';g.wave=0;dialogue([['Senti','Xong rồi! Bà cụ, đưa tay cho ta—'],['Fu Hua','...Còn một đợt nữa.'],['Senti','Không. Ta vừa hạ hết chúng rồi mà.'],['Senti','Bàn tay lại xuyên qua... Bà ấy bị kéo trở lại đúng chỗ cũ.'],['Senti','Mỗi lần đèn chớp, mọi thứ bắt đầu lại. Phải phá thứ đang giữ bà ấy ở đây!']],()=>{g.phase='arena';spawnWave();});")
s=s.replace("if(!g||screen!=='play'||['paused','finished','dialogue'].includes(g.phase))return;", "if(!g||screen!=='play')return;if(!['paused','finished','upgrade'].includes(g.phase)){g.presentationTime+=dt;g.dialogueClock+=dt;}if(['paused','finished','dialogue','upgrade'].includes(g.phase))return;")
s=s.replace("g.time+=dt;g.elapsed+=dt;", "g.time+=dt;g.elapsed+=dt;for(const k of ['dash','dashCD','dodgeCombo','survivorBuff'])g[k]=Math.max(0,(g[k]||0)-dt);")
s=s.replace("updateCombat(dt);if(g.mode==='story')updateStory(dt);", "updateCombat(dt);for(const bolt of g.projectiles){bolt.x+=bolt.vx*dt;bolt.life-=dt;if(Math.abs(bolt.x-p.x)<24&&Math.abs(bolt.y-(p.y-p.h/2))<p.h/2){if(g.parry>0){bolt.life=0;g.empowered=true;metric('perfect_parry');}else {damage(bolt.damage,bolt.x);bolt.life=0;}}}g.projectiles=g.projectiles.filter(b=>b.life>0);if(g.mode==='story')updateStory(dt);else if(g.phase==='explore'&&g.time>=g.nextUpgrade){showUpgrade();pressed.clear();return;}")
s=s.replace("`${p.attack.weapon}_attack_${p.attack.step}`", "`${p.attack.weapon}_attack_${Math.min(3,p.attack.step)}`")
s=s.replace("if(g.phase==='dialogue'&&!save.introSeen)", "if(false&&g.phase==='dialogue'&&!save.introSeen)")
s=s.replace("if(g.phase==='dialogue'&&g.arena?.m===2000&&g.dialogueIndex>=6)", "if(g.phase==='dialogue'&&g.arena?.m===2000&&g.memories.has('main-1')&&g.dialogueIndex>=11)")
s=s.replace("drawStoryOverlay();ctx.restore();updateHUD();", "drawStoryOverlay();drawNarrative();ctx.restore();updateHUD();")
s=s.replace("drawState(Math.floor(g.time/2)%2?'hurt':'fu_hua_assist',720,455,g.time,1,.45);", "drawFuHuaLoop();")
s=s.replace("label('KIẾM · ĐẾN GẦN ĐỂ RÚT'", "label('E · CHẠM VÀO KÝ ỨC'")
s=s.replace("'NÚT LẶP · J CHÉM'", "(g.loopCount?'NÚT GIỮ FU HUA · J CHÉM':'MỘT NHỊP SÁNG KHÁC THƯỜNG')")
s=s.replace("function say(speaker,text){g.speech={speaker,text};g.speechTime=6;", "function say(speaker,text){if(g.speechTime>0)g.speechQueue.push({speaker,text});else {g.speech={speaker,text};g.speechTime=5;} ")
s=s.replace("const p=g.p,scene=currentScene();", "const p=g.p,scene=currentScene();if(g.speechTime<=0&&g.speechQueue.length){g.speech=g.speechQueue.shift();g.speechTime=5;}updateNarrative(dt);")
s=s.replace("if(scene.line)say('Senti',scene.line)", "if(scene.line)say('Senti',scene.line);if(stats(save).sets.training_memory>=3)g.hp=Math.min(maxHP(),g.hp+maxHP()*.15)")
s=s.replace("if(Math.abs(p.x-chapter.swordCrystal.m*64)<65)", "if(Math.abs(p.x-chapter.swordCrystal.m*64)<80&&pressed.has('KeyE'))")
s=s.replace("say('Senti','Ha! Ít ra vũ khí vẫn gọi được.');", "dialogue([['Senti','...Chạm được rồi.'],['Senti','Nghe thấy ta chưa? Ta ở ngay đây!']],()=>{g.phase='explore';g.storyEvents.add('sword-awake');g.enemies.push(spawnEnemy('enemy',p.x+420,'first-witness'));say('Senti','Giờ thì chúng quay lại nhìn ta rồi. Tốt. Thử xem!');});")
s=s.replace("g.memories.add(m.id);dialogue", "g.memories.add(m.id);grantGear(save,m.id==='hidden-1'?'nagazora_survivor:T':'nagazora_survivor:B');g.memoryVision=m.id;dialogue")
s=s.replace("g.phase='explore';say('Ký ức'", "g.phase='explore';g.memoryVision=null;say('Ký ức'")
s=s.replace('damage(6,zone.x)','damage(155,zone.x)').replace('damage(8,d.x)','damage(195,d.x)').replace('g.debrisClock>7','g.debrisClock>4.5').replace('g.collapseX+=180*dt','g.collapseX+=250*dt').replace('damage(10,g.collapseX)','damage(240,g.collapseX)')
s=s.replace("if(g.speechTime>0&&g.speech&&g.phase!=='dialogue')", "if(false&&g.speechTime>0&&g.speech&&g.phase!=='dialogue')")
s=s.replace("$('#distance').innerHTML=`${String(Math.floor(g.p.x/64)).padStart(4,'0')} <small>M</small>`", "$('#distance').innerHTML=g.mode==='story'?`<small>${g.memories.size} / 3 KÝ ỨC</small>`:`${String(Math.floor(g.p.x/64)).padStart(4,'0')} <small>M</small>`")
a=s.index(" $('#objective').textContent=");b=s.index("\n $$('[data-weapon]')",a)
s=s[:a]+" $('#objective').textContent=narrativeObjective();"+s[b:]
s=s.replace("['dialogue','dying','finished'].includes(g.phase)","['dialogue','dying','finished','upgrade'].includes(g.phase)")
s=s.replace("$('#gear-back').onclick=()=>{switchScreen('home');syncHome()}","$('#gear-back').onclick=()=>{switchScreen('home');syncHome()}")
s=s.replace("$('#complete-home').onclick=gear", "$('#complete-home').onclick=()=>{save=structuredClone(committed);gear()}")
s=s.replace("scene:g?currentScene().id:null", "scene:g?currentScene().id:null,storyEvents:g?[...g.storyEvents]:[],interaction:g?.interaction,projectiles:g?.projectiles,rescueState:g?.rescueState,upgrades:g?.upgrades,dialogueIndex:g?.dialogueIndex")
s=s.replace("save=newSave();persist();", "g=null;save=ensureGear(newSave());persist();")
p.write_text(s,encoding='utf-8')
p=R/'serve.cjs';s=p.read_text(encoding='utf-8-sig').replace('4180','4181').replace('story v3','v4');p.write_text(s,encoding='utf-8')
p=R/'index.html';s=p.read_text(encoding='utf-8-sig').replace('</head>','<link rel="stylesheet" href="loadout.css"><link rel="stylesheet" href="narrative.css"></head>')
s=s.replace('<div id="save-summary"', '<p id="endless-record" class="mode-description"></p><div id="save-summary"')
s=s.replace('<span>2.000 m <b>·</b> 6 trận chiến <b>·</b> 8–12 phút</span>', '<span>Tỉnh lại → Tìm giọng nói → Phá vòng lặp</span>')
s=s.replace('<div id="objective"', '<div id="interaction-prompt" class="interaction-prompt" hidden></div><div id="upgrade-panel" class="veil" hidden><div class="panel"><span class="eyebrow">ENDLESS / NÂNG CẤP TRONG LƯỢT</span><h2>Giữ lấy một khả năng.</h2><p>Mỗi 30 giây, chọn một. Hiệu ứng kết thúc cùng lượt chơi.</p><button data-run-upgrade="power" class="primary">SỨC MẠNH · +15% sát thương</button><button data-run-upgrade="heal" class="secondary">HỒI PHỤC · +35% HP tối đa</button><button data-run-upgrade="guard" class="secondary">BẢO HỘ · Bất tử 8 giây</button></div></div><div id="objective"')
s=s.replace('<button id="return-home"', '<button id="checkpoint-gear" class="secondary">TRANG BỊ · TRỞ LẠI CHECKPOINT</button><button id="return-home"')
s=s.replace('<kbd>K</kbd> Phản đòn','<kbd>K</kbd> Phản đòn <kbd>L</kbd> Né <kbd>E</kbd> Tương tác')
s=s.replace('<button data-key="KeyK">ĐỠ</button>','<button data-key="KeyK">ĐỠ</button><button data-key="KeyL">NÉ</button><button data-key="KeyE">TƯƠNG TÁC</button>')
s=s.replace('KÝ ỨC #7,203','ĐÔ THỊ BỊ LÃNG QUÊN').replace('120 / 120','1000 / 1000')
p.write_text(s,encoding='utf-8')
print('Integrated v4 runtime and loadout')
