const {chromium}=require('./playwright-runtime.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
await p.goto('http://127.0.0.1:4181/build/?qa=1');await p.waitForFunction(()=>!document.querySelector('#story').disabled);assert.equal(await p.evaluate(()=>typeof window.__qa),'undefined');assert(await p.locator('#endless').isEnabled());await p.screenshot({path:path.join(__dirname,'../qa/build-home.png'),fullPage:true});
await p.locator('#gear').click();await p.locator('[data-tab=core]').first().click();await p.locator('[data-core=infinite_intimidator]').click();assert(await p.locator('[data-equip-core=infinite_intimidator]').isDisabled());await p.locator('[data-tab=stigma]').first().click();await p.locator('[data-set=shattered_swords]').click();await p.screenshot({path:path.join(__dirname,'../qa/build-equipment.png'),fullPage:true});await p.locator('#open-stigma-forge').click();assert.equal(await p.locator('[data-forge-kind=stigma]').getAttribute('class'),'active');assert.equal(await p.locator('[data-craft]').count(),11);assert.equal(await p.locator('.forge-art').count(),11);assert(await p.locator('[data-craft="attila:M"]').isVisible());assert(await p.locator('[data-craft="attila:M"]').isDisabled());assert(await p.locator('[data-craft="dirac:T"]').isDisabled());await p.screenshot({path:path.join(__dirname,'../qa/build-stigma-forge.png'),fullPage:true});await p.locator('[data-forge-kind=weapon]').click();assert.equal(await p.locator('[data-craft]').count(),6);assert(await p.locator('[data-craft=infinite_intimidator]').isDisabled());await p.screenshot({path:path.join(__dirname,'../qa/build-forge.png'),fullPage:true});await p.locator('#gear-back').click();await p.locator('#new-story').click();assert(await p.locator('#journey-dialog').isVisible());await p.locator('#journey-dialog .dialog-heading button').click();await p.locator('#story').click();
for(let i=0;i<14;i++)await p.locator('#next-dialogue').click();await p.locator('#dialogue').waitFor({state:'hidden'});await p.keyboard.down('KeyD');await p.locator('#interaction-prompt').waitFor({state:'visible'});await p.keyboard.up('KeyD');assert((await p.locator('#interaction-prompt').textContent()).toLowerCase().includes('kiếm'));await p.keyboard.press('KeyE');for(let i=0;i<4;i++)await p.locator('#next-dialogue').click();await p.locator('#dialogue').waitFor({state:'hidden'});assert(await p.locator('[data-weapon=sword]').isEnabled());await p.keyboard.press('Escape');assert(await p.locator('#pause-panel').isVisible());await p.screenshot({path:path.join(__dirname,'../qa/build-first-sword.png')});
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../qa/build-manifest.json')));for(const file of manifest){const r=await p.request.get('http://127.0.0.1:4181/build/'+file.file);assert.equal(r.status(),200,file.file);}assert.equal(errors.length,0);fs.writeFileSync(path.join(__dirname,'../qa/build-smoke.json'),JSON.stringify({files:manifest.length,errors,productionQA:false,realKeyboardSwordPickup:true,weaponForgeRecipes:6,stigmaForgeRecipes:11},null,2));console.log('Production smoke PASS:',manifest.length,'files, keyboard E sword pickup, weapon + stigma forge, no QA hooks');await b.close();})().catch(e=>{console.error(e);process.exit(1)});



