import assert from 'node:assert/strict';
import {newSave,readSave,SAVE_KEY,makeWorld,jumpRange} from '../engine.js';
import {ensureGear,grantGear,stats,equipCore,equipStigma,upgrade,upgradeCost,storePreset,applyPreset} from '../gear-system.js';
import {sanitizeSave} from '../save-validation.js';
import {canCraft,craft} from '../story-crafting.js';
import fs from 'node:fs';
const s=ensureGear(newSave()),base=stats(s);
assert.deepEqual([s.level,s.gold,s.weapons.length,Object.keys(s.cores).length],[1,0,0,0]);assert.equal(base.hp,1000);assert.equal(base.atk,100);assert.equal(equipCore(s,'domain_sentience'),false);
grantGear(s,'armored_bracers');assert.equal(stats(s).atk,100);equipCore(s,'armored_bracers');assert(stats(s).atk>100);
assert.equal(upgrade(s,'armored_bracers'),false);s.gold=10000;s.materials=20;let before=s.gold;assert(upgrade(s,'armored_bracers'));assert(s.gold<before);assert.equal(s.cores.armored_bracers.level,2);
for(let i=0;i<8;i++)upgrade(s,'armored_bracers');assert(upgradeCost(s,'armored_bracers').breakthrough);const alloy=s.materials;upgrade(s,'armored_bracers');assert.equal(s.cores.armored_bracers.cap,20);assert(s.materials<alloy);
for(const slot of ['T','M','B']){grantGear(s,'attila:'+slot);equipStigma(s,slot,'attila:'+slot);}assert.equal(stats(s).sets.attila,3);assert.equal(equipStigma(s,'T','attila:M'),false);
storePreset(s,'Story');equipCore(s,null);equipStigma(s,'T',null);assert(applyPreset(s,'Story'));assert.equal(stats(s).sets.attila,3);assert(s.equippedCore);
const clean=sanitizeSave({...s,slots:{T:'<script>alert(1)</script>',M:'attila:M',B:null},gold:-100,skills:{sword:1000},presets:{Boss:{core:'forged',slots:{T:'bad'}}}});assert.equal(clean.slots.T,null);assert.equal(clean.gold,0);assert.equal(clean.skills.sword,5);assert.equal(clean.presets.Boss.core,null);assert.equal(sanitizeSave({version:4,level:Infinity}),null);
const store=new Map([[SAVE_KEY,'{broken'],[SAVE_KEY+'-backup',JSON.stringify(s)]]);assert.equal(readSave({getItem:k=>store.get(k)}).gold,s.gold);
const chapter=JSON.parse(fs.readFileSync(new URL('../level-chapter-1.json',import.meta.url))),library=JSON.parse(fs.readFileSync(new URL('../endless-patterns.json',import.meta.url))),world=makeWorld(chapter,library);
assert.equal(world.patterns.length,chapter.placements.length);assert.equal(new Set(world.patterns.map(p=>p.id)).size,53);assert(world.platforms.some(p=>p.crumble));for(const gap of world.gaps)assert(gap.w<=jumpRange(chapter.physics.speed,chapter.physics.gravity,chapter.physics.jumpVelocity)*.85);
const savedAgain=sanitizeSave({...s,checkpoint:{m:1315,hp:700}});assert.equal(savedAgain.checkpoint.m,1315);
const low=stats(s,{combo:10}),high=stats(s,{combo:31});assert.equal(low.move,0);assert.equal(high.move,.15);assert(high.def>low.def);assert.equal(high.physical,.31);assert.equal(high.critDamage,1.8);assert(high.crit<.4,'CRT +40% is not +40% crit chance');
const old=ensureGear({...newSave(),cores:{cloth_resolve:{level:2,cap:10}},equippedCore:'cloth_resolve',stigmaInventory:{'training_memory:T':{level:1}},slots:{T:'training_memory:T',M:null,B:null}});assert(old.cores.armored_bracers);assert.equal(old.equippedCore,'armored_bracers');assert.equal(old.slots.T,'attila:T');assert.equal(Object.keys(old.cores).length,1);
assert.doesNotThrow(()=>sanitizeSave({...newSave(),cores:3,slots:'bad',presets:[],equippedCore:42}));
grantGear(s,'domain_sentience');assert.equal(equipCore(s,'domain_sentience'),true);s.presets.Boss={core:'domain_sentience',slots:{T:null,M:null,B:null}};assert.equal(applyPreset(s,'Boss'),true);
for(const slot of ['T','M','B']){grantGear(s,'marco_polo:'+slot);equipStigma(s,slot,'marco_polo:'+slot);}assert.equal(stats(s,{combo:31}).physical,.3);assert.equal(stats(s,{combo:31}).critDamage,2);
const tai=ensureGear(newSave());tai.chapters=[1,2,3,4,5];tai.storyEvents=['forge-tai-xuan'];tai.gold=2000;tai.materials=30;tai.forgeParts.taixuan_script=8;assert(canCraft(tai,'grips_tai_xuan'));assert(craft(tai,'grips_tai_xuan'));assert(tai.cores.grips_tai_xuan);assert(equipCore(tai,'grips_tai_xuan'));
const stigmaForge=ensureGear(newSave());stigmaForge.chapters=[1,2,3,4];stigmaForge.storyEvents=['forge-dirac'];stigmaForge.gold=5000;stigmaForge.materials=100;stigmaForge.crystals=100;stigmaForge.forgeParts.dirac_residue=12;assert(canCraft(stigmaForge,'dirac:T'));assert(craft(stigmaForge,'dirac:T'));assert(stigmaForge.stigmaInventory['dirac:T']);assert(equipStigma(stigmaForge,'T','dirac:T'));
console.log('PASS: blank save, ownership, upgrades + breakthrough, T/M/B and presets, bounded import, backup recovery, 53 authored layouts and jump limits.');
