import {CORES,SETS,ensureGear,stats,equipCore,equipStigma,upgradeCost,upgrade,recommended,storePreset,applyPreset} from './gear-system.js';
import {SAVE_KEY} from './engine.js';
import {RECIPES,FORGE_MATERIALS,recipeNeeds,canCraft,craft,ownsRecipeItem} from './story-crafting.js';
import {manualSaveKey} from './story-sessions.js';
let tab='character',selectedCore='armored_bracers',selectedSet='attila',forgeKind='weapon';
const stars=n=>'★'.repeat(n),fmt=(k,v)=>['crit','physical','normal','reduction','move'].includes(k)?Math.round(v*100)+'%':Math.round(v).toLocaleString('vi-VN');
const coreArt=c=>`<span class="core-art" style="background-image:url('assets/wiki-redraws/${c.art}');background-position:${c.artIndex%2*100}% ${Math.floor(c.artIndex/2)*100}%"></span>`;
const stigmaArt=(set,i)=>`<span class="stigma-art" style="background-image:url('assets/${set.pieceFiles?'wiki-source-art/'+set.pieceFiles[i]:'wiki-redraws/'+set.file}');${set.pieceFiles?'background-size:100% 100%;':''}background-position:${i*50}% 50%"></span>`;
const materialIcon=id=>{const icon=FORGE_MATERIALS[id].icon,x=(icon%5)*25,y=Math.floor(icon/5)*50;return `<span class="material-icon" style="background-position:${x}% ${y}%" aria-hidden="true"></span>`};
const materialCost=(id,owned,count)=>`<span class="forge-material ${owned<count?'short':''}">${materialIcon(id)}<span>${FORGE_MATERIALS[id].name}<small>${owned}/${count}</small></span></span>`;
export function renderLoadout({save:s,changed,resume,draw}){
 ensureGear(s);const v=stats(s),power=Math.round(v.atk*3+v.def*2+v.hp*.1+(s.weapons||[]).reduce((sum,id)=>sum+(s.weaponLevels?.[id]||0)*18,0)+Object.values(s.stigmaInventory||{}).reduce((sum,item)=>sum+(item.level||0)*2,0)+Object.values(s.cores||{}).reduce((sum,item)=>sum+(item.level||0)*3,0)),root=document.querySelector('#inventory');
 const tabs=[['character','Nhân vật'],['core','Vũ khí'],['stigma','Vết Thánh'],['forge','Bàn rèn'],['skills','Kỹ năng'],['presets','Preset & Save']];
 const statsHTML=(a,b)=>['hp','atk','def','crit'].map(k=>`<div><span>${k.toUpperCase()}</span><b>${fmt(k,a[k])}</b>${b?`<em class="${b[k]>=a[k]?'plus':'minus'}">→ ${fmt(k,b[k])}</em>`:''}</div>`).join('');
 const activeSets=SETS.filter(set=>v.sets[set.id]);
 const bonuses=activeSets.length?activeSets.map(set=>`<article class="set-status"><strong>${set.name} · ${v.sets[set.id]}/3</strong><p class="${v.sets[set.id]>=2?'plus':'dim'}">2 món · ${set.two}</p><p class="${v.sets[set.id]>=3?'plus':'dim'}">3 món · ${set.three}</p></article>`).join(''):'<p class="empty-note">Chưa mặc Vết Thánh. Chưa có hiệu ứng bộ.</p>';
 root.innerHTML=`<div class="resource-strip"><span>⚔ ${power} Sức mạnh</span><span>◈ ${s.gold.toLocaleString('vi-VN')} Coin</span><span>◇ ${s.crystals} Tinh thể</span><span>⬡ ${s.materials} Hợp kim</span><span>✧ ${s.torus} Torus</span><span class="resource-part">${materialIcon('namiko_coil')}${s.forgeParts.namiko_coil||0} Cuộn mạch Namiko</span></div><nav class="loadout-tabs" aria-label="Trang bị">${tabs.map(([id,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${name}</button>`).join('')}</nav><div class="loadout-layout"><aside class="character-panel"><div class="character-stage"><canvas id="loadout-portrait" width="370" height="300"></canvas><span>HERRSCHER OF SENTIENCE</span></div><div class="character-level"><b>Senti · Lv. ${s.level}</b><small>Sức mạnh trang bị ${power} · EXP ${s.xp} / ${s.level*150}</small><i style="--xp:${s.xp/(s.level*150)*100}%"></i></div><div class="stat-grid">${statsHTML(v)}</div><div class="companion-card">${s.assistUnlocked?'Fu Hua · Song Hành đã mở':s.chapter===2?'Fu Hua · Đang chạy cùng':'Fu Hua · Chưa gia nhập'}<small>${s.assistUnlocked?'Edge of Taixuan':s.chapter===2?'Tự né chướng ngại · Chưa mở Assist':'Đồng hành Chương 2 · Assist Chương 3'}</small></div><button id="continue-loadout" class="primary">TIẾP TỤC STORY →</button></aside><div class="equipment-pane" id="equipment-pane"></div></div>`;
 const pane=root.querySelector('#equipment-pane');
 const costButton=id=>{const c=upgradeCost(s,id);return c?`<button data-upgrade="${id}" class="secondary" ${s.gold<c.gold||s.materials<c.alloy?'disabled':''}>${c.breakthrough?'ĐỘT PHÁ':'CƯỜNG HÓA'} · ${c.gold} Coin${c.alloy?' + '+c.alloy+' Hợp kim':''}</button>`:'<span class="dim">Chưa sở hữu hoặc đã đạt cấp tối đa</span>'};
 if(tab==='character'){
  const c=CORES.find(c=>c.id===s.equippedCore);
  pane.innerHTML=`<div class="pane-heading"><div><h2>Bộ trang bị hiện tại</h2><p>Một ô Gauntlets dùng chung cho ba hình thái Kiếm / Thương / Xích.</p></div><button id="recommend" class="secondary">ĐỀ XUẤT</button></div><div class="equipped-layout"><button data-tab="core" class="core-slot">${c?coreArt(c):'<span class="empty-symbol">◇</span>'}<small>VŨ KHÍ · GAUNTLETS</small><b>${c?c.name:'TRỐNG'}</b><em>${c?stars(c.rarity):'Chưa nhận trong Story'}</em></button><div class="stigma-slots">${['T','M','B'].map((slot,i)=>{const id=s.slots[slot],set=id?SETS.find(a=>id.startsWith(a.id+':')):null;return `<button data-tab="stigma" class="stigma-slot">${set?stigmaArt(set,i):'<span class="empty-symbol">'+slot+'</span>'}<small>${slot} · ${['TRÊN','GIỮA','DƯỚI'][i]}</small><b>${set?set.name:'TRỐNG'}</b></button>`}).join('')}</div></div>${bonuses}<div class="forms-row">${['sword','spear','chain'].map((id,i)=>`<div class="${s.weapons.includes(id)?'':'dim'}"><b>${['KIẾM','THƯƠNG','XÍCH'][i]}</b><small>${s.weapons.includes(id)?'Đã mở hình thái':['Khối ký ức Nagazora','Chương 2 · Arc City','Chương 4 · Babylon'][i]}</small></div>`).join('')}</div>`;
 }else if(tab==='core'){
  const c=CORES.find(c=>c.id===selectedCore),own=s.cores[c.id],preview=structuredClone(s);if(own)equipCore(preview,c.id);
  pane.innerHTML=`<div class="pane-heading"><div><h2>Vũ khí</h2><p>Chọn vũ khí để xem hình, hiệu ứng và nơi nhận trong Story.</p></div></div><div class="core-grid">${CORES.map(c=>`<button data-core="${c.id}" class="item-card ${selectedCore===c.id?'selected':''} ${s.cores[c.id]?'':'locked'}">${coreArt(c)}<b>${c.name}</b><em>${stars(c.rarity)}</em><small>${s.cores[c.id]?'Lv. '+s.cores[c.id].level+(s.equippedCore===c.id?' · ĐANG MẶC':''):'CHƯA NHẬN'}</small></button>`).join('')}</div><article class="item-detail"><h3>${c.name} <em>${stars(c.rarity)}</em></h3><p>${c.passive}</p><p class="wiki-meta">HI3 · ${c.rarity}–${c.maxRarity}★ · ATK ${c.atk} / CRT ${c.crt} ở cấp tối đa · <a href="${c.wiki}" target="_blank" rel="noopener noreferrer">Xem wiki ↗</a></p><p>${c.available?(c.runtime||"Không có kỹ năng riêng. Chỉ số tăng theo cấp trang bị trong bản 2D."):"Chưa mở trong Chương 1. Mô tả trên là hiệu ứng trong HI3."}</p><p class="dim">Nhận trong bản fan game: ${c.source}${own?` · Lv. ${own.level}/${own.cap} · Giới hạn ${c.max}`:''}</p><div class="stat-grid compare">${statsHTML(v,own?stats(preview):null)}</div><div class="detail-actions"><button data-equip-core="${c.id}" class="primary" ${own&&c.available?'':'disabled'}>${s.equippedCore===c.id?'ĐANG TRANG BỊ':'TRANG BỊ'}</button><button id="unequip-core" class="secondary" ${s.equippedCore?'':'disabled'}>GỠ VŨ KHÍ</button>${costButton(c.id)}</div>${!own?'<p class="dim">Chưa sở hữu. Chỉ số này chưa được cộng cho nhân vật.</p>':''}</article>`;
 }else if(tab==='stigma'){
  const set=SETS.find(a=>a.id===selectedSet);
  pane.innerHTML=`<div class="pane-heading"><div><h2>Vết Thánh · T / M / B</h2><p>${set.rarity}–${set.maxRarity}★ · <a href="${set.wiki}" target="_blank" rel="noopener noreferrer">Xem bộ gốc trên wiki ↗</a> · Hiệu ứng bên dưới áp dụng trong bản 2D.</p></div><button id="open-stigma-forge" class="secondary">RÈN VẾT THÁNH →</button></div><div class="set-tabs">${SETS.map(a=>`<button data-set="${a.id}" class="${selectedSet===a.id?'selected':''}">${a.name}<em>${stars(a.rarity)}</em></button>`).join('')}</div><div class="stigma-cards">${['T','M','B'].map((slot,i)=>{const id=set.id+':'+slot,own=s.stigmaInventory[id],preview=structuredClone(s);if(own)equipStigma(preview,slot,id);return `<article>${stigmaArt(set,i)}<h3>${set.pieceNames[i]}</h3><p>${set.parts[i]}</p><small>${own?'Lv. '+own.level+'/'+set.maxLevel:set.source}</small>${own?`<div class="mini-compare">ATK ${v.atk} → ${stats(preview).atk} · HP ${v.hp} → ${stats(preview).hp}</div>`:''}<button data-equip-stigma="${id}" class="primary" ${own?'':'disabled'}>${s.slots[slot]===id?'ĐANG MẶC':own?'TRANG BỊ':'CHƯA NHẬN'}</button><button data-clear-slot="${slot}" class="secondary" ${s.slots[slot]?'':'disabled'}>GỠ Ô ${slot}</button>${costButton(id)}</article>`}).join('')}</div><article class="set-status"><strong>${set.name} · ${v.sets[set.id]||0}/3 đang mặc</strong><p class="${v.sets[set.id]>=2?'plus':'dim'}">2 món · ${set.two}</p><p class="${v.sets[set.id]>=3?'plus':'dim'}">3 món · ${set.three}</p></article>`;
 }else if(tab==='forge'){
  const forgeRecipes=RECIPES.filter(r=>(r.id.includes(':')?'stigma':'weapon')===forgeKind);
  pane.innerHTML=`<h2>Bàn rèn ký ức</h2><p>${forgeKind==='stigma'?'Mỗi mảnh T / M / B được rèn riêng. Attila dùng nguyên liệu đầu game; Dirac, Shattered Swords và Pericles cần mảnh nhận diện riêng từ Endless. Marco Polo được thu thập trực tiếp trong cốt truyện Chương 1.':'Vũ khí từ 4★ cần bản thiết kế trong Story và mảnh riêng. Endless rơi nguyên liệu ngẫu nhiên mỗi 500 m từ mốc 750 m; viên gạch là phần thưởng nhiệm vụ đặc biệt.'}</p><div class="forge-kind-tabs"><button data-forge-kind="weapon" class="${forgeKind==='weapon'?'active':''}">RÈN VŨ KHÍ</button><button data-forge-kind="stigma" class="${forgeKind==='stigma'?'active':''}">RÈN VẾT THÁNH T / M / B</button></div><div class="forge-grid">${forgeRecipes.map(r=>{const unlocked=s.storyEvents.includes(r.event),owned=ownsRecipeItem(s,r.id),future=r.available===false||!s.chapters.includes(r.chapter),ready=canCraft(s,r.id);const parts=recipeNeeds(s,r);return `<article class="forge-recipe ${future?'future':''}"><div class="forge-art">${r.id.includes(':')?stigmaArt(SETS.find(set=>r.id.startsWith(set.id+':')),['T','M','B'].indexOf(r.id.split(':')[1])):coreArt(CORES.find(c=>c.id===r.id))}</div><small class="forge-tier">${r.rarity}★ · ${future?'CHƯƠNG '+r.chapter+' · CHƯA MỞ':'CHƯƠNG '+r.chapter}</small><h3>${r.name}</h3><p>${r.story}</p><div class="forge-ingredients">${materialCost('alloy',s.materials,r.materials)}${r.crystals?materialCost('crystal',s.crystals,r.crystals):''}${r.torus?materialCost('torus',s.torus,r.torus):''}${parts.map(part=>materialCost(part.id,part.owned,part.count)).join('')}</div><p class="forge-cost">◈ ${r.gold} Coin${r.base?' · Cần '+CORES.find(c=>c.id===r.base).name:''}</p>${parts.map(part=>`<small class="forge-source">${part.name}: ${part.source}</small>`).join('')}<small class="forge-state">${owned?'Đã sở hữu':future?'Đang chờ Chương '+r.chapter:unlocked?'Đã tìm được bản thiết kế':'Tìm bản thiết kế trong Story'}</small><button data-craft="${r.id}" class="primary" ${ready?'':'disabled'}>${owned?'ĐÃ HOÀN THÀNH':future?'CHƯƠNG SAU':!unlocked?'CHƯA CÓ BẢN THIẾT KẾ':ready?'RÈN TRANG BỊ':'CHƯA ĐỦ NGUYÊN LIỆU'}</button></article>`}).join('')}</div>`;
 }else if(tab==='skills'){
  pane.innerHTML=`<h2>Hình thái & kỹ năng</h2><p>Mở kỹ năng bằng cốt truyện. Nâng kỹ năng dùng Tinh thể Ký ức.</p><div class="skill-grid">${[['sword','Kiếm · Tốc','Chém +5% sát thương mỗi cấp',s.weapons.includes('sword')],['dodge','Né · Phản','L né nhanh · Giảm hồi chiêu theo cấp',s.weapons.includes('sword')],['spear','Thương · Phá','Phá giáp · Mở Chương 2',false],['chain','Xích · Khống','Gom quái · Mở Chương 4',false],['assist','Song Hành','Edge of Taixuan · Mở Chương 3',false],['dual','Dual Combo','Phối hợp cùng Fu Hua · Mở Chương 5',false]].map(([id,name,desc,open])=>`<article class="${open?'':'locked'}"><h3>${name}</h3><p>${desc}</p><strong>${open?'Lv. '+(s.skills[id]||0)+'/5':'CHƯA MỞ'}</strong><button data-skill="${id}" class="secondary" ${!open||(s.skills[id]||0)>=5||s.crystals<5*((s.skills[id]||0)+1)?'disabled':''}>NÂNG · ${5*((s.skills[id]||0)+1)} TINH THỂ</button></article>`).join('')}</div>`;
 }else{
  pane.innerHTML=`<h2>Bộ trang bị đã lưu</h2><div class="preset-grid">${['Story','Boss','Endless','Tự chọn'].map(name=>`<article><h3>${name}</h3><p>${s.presets[name]?CORES.find(c=>c.id===s.presets[name].core)?.name||'Chưa mặc vũ khí':'Chưa lưu bộ trang bị'}</p><button data-save-preset="${name}" class="secondary">LƯU BỘ HIỆN TẠI</button><button data-load-preset="${name}" class="primary" ${s.presets[name]?'':'disabled'}>ÁP DỤNG</button></article>`).join('')}</div><div class="save-tools"><h3>Mang tiến trình sang máy khác</h3><p>Xuất file lưu hiện tại. Khi nhập, bản lưu đang dùng sẽ được cất riêng.</p><button id="export-save" class="secondary">XUẤT SAVE JSON</button><label class="secondary">NHẬP SAVE<input id="import-save" type="file" accept=".json" hidden></label><p id="save-feedback" role="status"></p></div>`;
 }
 if(tab==='presets'){
  const section=document.createElement('div');section.className='manual-saves';section.innerHTML='<h3>Ba ô lưu thủ công</h3><p>Khôi phục một ô sẽ cất bản đang chơi riêng trước khi chuyển.</p>';
  for(let slot=1;slot<=3;slot++){
   let record;try{record=JSON.parse(localStorage.getItem(manualSaveKey(localStorage,slot)))}catch{}
   const card=document.createElement('article'),title=document.createElement('p');title.textContent=`Ô ${slot} · ${record?'Lv. '+record.save.level+' · Checkpoint '+record.save.checkpoint.m+' m':'Trống'}`;card.append(title);
   const keep=document.createElement('button');keep.className='secondary';keep.textContent='LƯU VÀO Ô '+slot;keep.onclick=()=>{try{const key=manualSaveKey(localStorage,slot),old=localStorage.getItem(key);if(old)localStorage.setItem(key+'-archive-'+Date.now(),old);localStorage.setItem(key,JSON.stringify({save:s}));rerender()}catch{keep.textContent='Không đủ chỗ lưu'}};card.append(keep);
   const restore=document.createElement('button');restore.className='secondary';restore.textContent='KHÔI PHỤC';restore.disabled=!record;restore.onclick=()=>{if(record)changed(record.save)};card.append(restore);section.append(card);
  }pane.append(section);
 }
 const rerender=()=>renderLoadout({save:s,changed,resume,draw}),commit=()=>{changed();rerender()};
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;rerender()});
 root.querySelectorAll('[data-forge-kind]').forEach(b=>b.onclick=()=>{forgeKind=b.dataset.forgeKind;rerender()});
 root.querySelector('#open-stigma-forge')?.addEventListener('click',()=>{tab='forge';forgeKind='stigma';rerender()});
 root.querySelectorAll('[data-core]').forEach(b=>b.onclick=()=>{selectedCore=b.dataset.core;rerender()});root.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{selectedSet=b.dataset.set;rerender()});
 root.querySelectorAll('[data-equip-core]').forEach(b=>b.onclick=()=>{if(equipCore(s,b.dataset.equipCore))commit()});root.querySelector('#unequip-core')?.addEventListener('click',()=>{equipCore(s,null);commit()});
 root.querySelectorAll('[data-equip-stigma]').forEach(b=>b.onclick=()=>{const id=b.dataset.equipStigma;if(equipStigma(s,id.split(':')[1],id))commit()});root.querySelectorAll('[data-clear-slot]').forEach(b=>b.onclick=()=>{equipStigma(s,b.dataset.clearSlot,null);commit()});
 root.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(upgrade(s,b.dataset.upgrade))commit()});root.querySelector('#recommend')?.addEventListener('click',()=>{recommended(s);commit()});
 root.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{const id=b.dataset.skill;if(!['sword','dodge'].includes(id)||!s.weapons.includes('sword'))return;const level=s.skills[id]||0,cost=5*(level+1);if(level>=5||s.crystals<cost)return;s.crystals-=cost;s.skills[id]=level+1;commit()});
 root.querySelectorAll('[data-save-preset]').forEach(b=>b.onclick=()=>{storePreset(s,b.dataset.savePreset);commit()});root.querySelectorAll('[data-load-preset]').forEach(b=>b.onclick=()=>{if(applyPreset(s,b.dataset.loadPreset))commit()});
 root.querySelector('#export-save')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='sentience-save-v4.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 root.querySelector('#import-save')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file||file.size>1000000)throw Error('File quá lớn');const value=JSON.parse(await file.text());if(value.version!==4||!Array.isArray(value.weapons)||!Array.isArray(value.cleared)||!value.checkpoint||!Number.isFinite(value.gold)||value.gold<0||!Number.isInteger(value.level)||value.level<1||value.level>50)throw Error('Save không hợp lệ');if(!changed(value))throw Error('Không nhập được');}catch(err){root.querySelector('#save-feedback').textContent=err.message}});
 root.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>{if(craft(s,b.dataset.craft))commit()});root.querySelector('#continue-loadout').onclick=resume;draw(root.querySelector('#loadout-portrait'),s.assistUnlocked||s.chapter===2);
}

