import {listSessions,createSession,selectSession,renameSession,exportSession,importSession} from './story-sessions.js';
export function journeyName(storage){return listSessions(storage).find(s=>s.active)?.name||'Hành trình';}
export function openJourneys(onLoad){
 let dialog=document.querySelector('#journey-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='journey-dialog';dialog.className='story-dialog';document.body.append(dialog);}
 const render=()=>{dialog.innerHTML='<form method="dialog" class="dialog-heading"><div><small>STORY / CÁC HÀNH TRÌNH</small><h2>Chọn phiên của bạn</h2></div><button class="secondary" aria-label="Đóng danh sách hành trình">ĐÓNG</button></form><p>Mỗi hành trình có tiến độ, vật phẩm và ô lưu riêng. Bạn có thể xuất thành file để cất giữ rồi tải lại trên máy khác.</p><div class="journey-transfer"><button id="import-journey" class="secondary" type="button">TẢI HÀNH TRÌNH LÊN</button><input id="import-journey-file" type="file" accept=".json,application/json" hidden><small>Chọn file .json đã xuất từ game.</small></div><div id="journey-list"></div><form id="create-journey" class="journey-create"><label>Tên hành trình mới<input name="name" maxlength="60" placeholder="Ví dụ: Lần hai · tìm đủ ký ức" required></label><button class="primary" type="submit">TẠO HÀNH TRÌNH MỚI</button></form><p id="journey-message" role="status"></p>';
  const list=dialog.querySelector('#journey-list');for(const item of listSessions(localStorage)){const card=document.createElement('article'),heading=document.createElement('h3'),status=document.createElement('p'),input=document.createElement('input'),rename=document.createElement('button'),download=document.createElement('button'),load=document.createElement('button');card.className='journey-card';card.dataset.journey=item.id;heading.textContent=item.name;status.textContent=`${item.active?'ĐANG CHỌN · ':''}Lv. ${item.level} · ${item.complete?'Hoàn thành Chương 1':'Checkpoint '+item.checkpoint+' m'}`;input.value=item.name;input.maxLength=60;input.setAttribute('aria-label','Đổi tên '+item.name);rename.className='secondary';rename.textContent='ĐỔI TÊN';rename.onclick=()=>attempt(()=>{renameSession(localStorage,item.id,input.value);render()});download.className='secondary';download.textContent='XUẤT HÀNH TRÌNH';download.onclick=()=>attempt(()=>{const data=exportSession(localStorage,item.id),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(item.name.replace(/[^a-z0-9À-ỹ _-]/gi,'').trim().replace(/\s+/g,'-')||'hanh-trinh')+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)});load.className='primary';load.textContent=item.active?'ĐANG CHỌN':'MỞ HÀNH TRÌNH';load.disabled=item.active;load.onclick=()=>attempt(()=>{if(!selectSession(localStorage,item.id))throw Error('Không đọc được phiên này. Bản đang chơi được giữ nguyên.');onLoad();dialog.close()});card.append(heading,status,input,rename,download,load);list.append(card);}
  const picker=dialog.querySelector('#import-journey-file');dialog.querySelector('#import-journey').onclick=()=>picker.click();picker.onchange=async()=>{const file=picker.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());importSession(localStorage,payload);onLoad();dialog.close()}catch(e){dialog.querySelector('#journey-message').textContent=e.message||'Không đọc được file hành trình.'}finally{picker.value=''}};
  dialog.querySelector('#create-journey').onsubmit=e=>{e.preventDefault();attempt(()=>{const name=new FormData(e.currentTarget).get('name');if(!createSession(localStorage,name))throw Error('Không tạo được hành trình.');onLoad();dialog.close()})};
 };const attempt=fn=>{try{fn()}catch(e){dialog.querySelector('#journey-message').textContent=e.message||'Không đủ chỗ lưu trên thiết bị.'}};render();dialog.showModal();
}
export function openAudioSettings(audio){let dialog=document.querySelector('#audio-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='audio-dialog';dialog.className='story-dialog audio-dialog';document.body.append(dialog);}dialog.innerHTML='<form method="dialog" class="dialog-heading"><div><small>ÂM THANH</small><h2>Nghe theo cách của bạn</h2></div><button class="secondary">ĐÓNG</button></form><p>Nhạc và mẫu âm thanh chiến đấu từ Honkai Impact 3rd. Voice là mẫu từ clip kỹ năng; hội thoại Story hiện có phụ đề.</p>'+[['music','Nhạc nền'],['sfx','Hiệu ứng đánh'],['voice','Voice chiến đấu · HoS / Fu Hua']].map(([key,name])=>`<label class="audio-slider">${name}<input data-audio-volume="${key}" type="range" min="0" max="100" value="${Math.round(audio.settings[key]*100)}"><output>${Math.round(audio.settings[key]*100)}%</output></label>`).join('');dialog.querySelectorAll('[data-audio-volume]').forEach(input=>input.oninput=()=>{audio.setVolume(input.dataset.audioVolume,+input.value/100);input.nextElementSibling.value=input.value+'%'});dialog.showModal();return dialog;}
